### ISSUE TITLE
Segmentation Fault error while training

### ISSUE THREAD

**Issue by gangubai** [satinder147/Face_recognition_attendance_system#1]
python3 trainer.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-09-29 14:45:54.055259: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-29 14:45:54.164054: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-29 14:45:54.164338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.51GiB
2018-09-29 14:45:54.164356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-09-29 14:45:54.338994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-29 14:45:54.339031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-09-29 14:45:54.339037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-09-29 14:45:54.339226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7254 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
Segmentation fault (core dumped)

research_centre_gpu@GPU:~/Attendance-using-Face-master$ python trainer.py
/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "trainer.py", line 13, in <module>
    e=emb()
  File "/home/research_centre_gpu/Attendance-using-Face-master/embedding.py", line 5, in __init__
    self.model=load_model('facenet_keras.h5')
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/engine/saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/engine/saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/engine/network.py", line 1017, in from_config
    process_layer(layer_data)
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/engine/network.py", line 1003, in process_layer
    custom_objects=custom_objects)
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/layers/core.py", line 730, in from_config
    function = func_load(config['function'], globs=globs)
  File "/home/research_centre_gpu/miniconda2/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 235, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

Also we removed the file __pycache__   to remove the  error ->ValueError: bad marshal data (unknown type code) and we successfully removed it but still facing the same issue.

Please help me to find the solution for this issue.
Thanks in advance!

**Comment by satinder147** [comment]
I think there is some problem loading the facenet keras model
I would suggest you to download this model from https://drive.google.com/drive/folders/12aMYASGCKvDdkygSv1yQq8ns03AStDO_
and try again

**Comment by satinder147** [comment]
Let me know if it works

**Comment by gangubai** [comment]
Sorry,but still facing the same errors for both if I run trainer.py in python2 and python3.

**Comment by satinder147** [comment]
It runs without any errors on my system. I am sure that the error is regarding loading the model. I will come back to you in a some days

**Comment by sadakmed** [comment]
the same for me, i think is python3.5, it works only on 3.6

**Comment by satinder147** [comment]
I found a solution. The reason why it is not working is because it is unable to load the architecture. Try finding a keras implementation of facenet and make a instance of that model and then try loading weights (facenet.h5)
