### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by arnold-anand** [satinder147/Face_recognition_attendance_system#19]
Traceback (most recent call last):
  File "C:\Users\arnol\Desktop\Attendance-using-Face-master\trainer.py", line 12, in <module>
    e = emb()
  File "C:\Users\arnol\Desktop\Attendance-using-Face-master\embedding.py", line 5, in __init__
    self.model=load_model('facenet_keras.h5')
  File "C:\Python 3.9\lib\site-packages\keras\saving\save.py", line 201, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "C:\Python 3.9\lib\site-packages\keras\saving\hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "C:\Python 3.9\lib\site-packages\keras\saving\model_config.py", line 59, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Python 3.9\lib\site-packages\keras\layers\serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Python 3.9\lib\site-packages\keras\utils\generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Python 3.9\lib\site-packages\keras\engine\training.py", line 2332, in from_config
    functional.reconstruct_from_config(config, custom_objects))
  File "C:\Python 3.9\lib\site-packages\keras\engine\functional.py", line 1274, in reconstruct_from_config
    process_layer(layer_data)
  File "C:\Python 3.9\lib\site-packages\keras\engine\functional.py", line 1256, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "C:\Python 3.9\lib\site-packages\keras\layers\serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Python 3.9\lib\site-packages\keras\utils\generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Python 3.9\lib\site-packages\keras\layers\core.py", line 1001, in from_config
    function = cls._parse_function_from_config(
  File "C:\Python 3.9\lib\site-packages\keras\layers\core.py", line 1053, in _parse_function_from_config
    function = generic_utils.func_load(
  File "C:\Python 3.9\lib\site-packages\keras\utils\generic_utils.py", line 783, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by smit479** [comment]
please
