### ISSUE TITLE
Not able to run trainer.py

### ISSUE THREAD

**Issue by atulvashisth96** [satinder147/Face_recognition_attendance_system#3]
When I'm running trainer.py on Pycharm it is showing

Using TensorFlow backend.
2018-10-05 15:20:41.521166: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "trainer.py", line 13, in <module>
    e=emb()
  File "C:\Users\Admin\Desktop\Programs\Attendance face recognition\Attendance-using-Face-master\Attendance-using-Face-master\embedding.py", line 5, in __init__
    self.model=load_model('facenet_keras.h5')
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\engine\network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Admin\PycharmProjects\untitled\venv\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "../code/facenet_keras_v1.py", line 90, in <lambda>
IndexError: tuple index out of range

Please resolve the issue
NOTE: I am running this on windows 10 and does not have GPU.

**Comment by atulvashisth96** [comment]
when running trainer.py
 File "../code/facenet_keras_v1.py", line 90, in <lambda>
IndexError: tuple index out of range

**Comment by shiva13425** [comment]
hi @atulvashisth96 
    is the issue solved?
